package keuangan;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.var;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

public class DlgSaldoAkunPerBulan extends javax.swing.JDialog {
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Jurnal jur=new Jurnal();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps;
    private ResultSet rs;
    private int i=0;
    private StringBuilder htmlContent;
    private double saldojanuari=0;
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgSaldoAkunPerBulan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(
                ".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#464646;}"+
                ".isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#464646;}"+
                ".isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#464646;}"+
                ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#464646;}"
        );
        Document doc = kit.createDefaultDocument();
        LoadHTML.setDocument(doc);
        LoadHTML.setDocument(doc);      
        
        Valid.LoadTahun(ThnCari);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kd2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        panelisi1 = new widget.panelisi();
        label11 = new widget.Label();
        ThnCari = new widget.ComboBox();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        btnCari = new widget.Button();
        BtnAll = new widget.Button();
        label9 = new widget.Label();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        Scroll = new widget.ScrollPane();
        LoadHTML = new widget.editorpane();

        Kd2.setName("Kd2"); // NOI18N
        Kd2.setPreferredSize(new java.awt.Dimension(207, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Laporan Bulanan HAIs ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(70, 70, 70))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tahun :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(45, 23));
        panelisi1.add(label11);

        ThnCari.setName("ThnCari"); // NOI18N
        ThnCari.setPreferredSize(new java.awt.Dimension(65, 23));
        panelisi1.add(ThnCari);

        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelisi1.add(jLabel6);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(170, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelisi1.add(TCari);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        btnCari.setMnemonic('2');
        btnCari.setToolTipText("Alt+2");
        btnCari.setName("btnCari"); // NOI18N
        btnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariKeyPressed(evt);
            }
        });
        panelisi1.add(btnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('M');
        BtnAll.setToolTipText("Alt+M");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelisi1.add(BtnAll);

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(80, 30));
        panelisi1.add(label9);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelisi1.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        LoadHTML.setBorder(null);
        LoadHTML.setName("LoadHTML"); // NOI18N
        Scroll.setViewportView(LoadHTML);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            
            File g = new File("file2.css");            
            BufferedWriter bg = new BufferedWriter(new FileWriter(g));
            bg.write(
                    ".isi td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#464646;}"+
                    ".isi2 td{font: 11px tahoma;height:12px;background: #ffffff;color:#464646;}"+                    
                    ".isi3 td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#464646;}"+
                    ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#464646;}"
            );
            bg.close();
            
            File f = new File("BulananHAIs.html");            
            BufferedWriter bw = new BufferedWriter(new FileWriter(f));            
            bw.write(LoadHTML.getText().replaceAll(
                    "<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                        "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                            "<tr class='isi2'>"+
                                "<td valign='top' align='center'>"+
                                    "<font size='4' face='Tahoma'>"+var.getnamars()+"</font><br>"+
                                    var.getalamatrs()+", "+var.getkabupatenrs()+", "+var.getpropinsirs()+"<br>"+
                                    var.getkontakrs()+", E-mail : "+var.getemailrs()+"<br><br>"+       
                                "</td>"+
                           "</tr>"+
                        "</table>")
            );
            bw.close();                         
            Desktop.getDesktop().browse(f.toURI());
        } catch (Exception e) {
            System.out.println("Notifikasi : "+e);
        }     
        
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt,ThnCari,BtnKeluar);
        }
    }//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnPrint,ThnCari);}
    }//GEN-LAST:event_BtnKeluarKeyPressed

private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
    prosesCari();
}//GEN-LAST:event_btnCariActionPerformed

private void btnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            btnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, ThnCari, BtnPrint);
        }
}//GEN-LAST:event_btnCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        prosesCari();
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            TCari.setText("");
            prosesCari();
        }else{
            Valid.pindah(evt, BtnPrint, BtnKeluar);
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnCariActionPerformed(null);
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
            btnCari.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
            BtnKeluar.requestFocus();
        }
    }//GEN-LAST:event_TCariKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgSaldoAkunPerBulan dialog = new DlgSaldoAkunPerBulan(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.TextBox Kd2;
    private widget.editorpane LoadHTML;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.ComboBox ThnCari;
    private widget.Button btnCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel6;
    private widget.Label label11;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    // End of variables declaration//GEN-END:variables

    private void prosesCari() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='2%' rowspan='2'>Kode Akun</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='6%' rowspan='2'>Akun Rekening</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>Januari</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>Februari</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>Maret</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>April</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>Mei</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>Juni</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>Juli</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>Agutus</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>September</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>Otober</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>November</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center' width='7%' colspan='4'>Desember</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Awal</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Debet</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Kredit</td>"+
                    "<td valign='middle' bgcolor='#fafff5' align='center'>Saldo Akhir</td>"+
                "</tr>"
            );     
            ps=koneksi.prepareStatement("select kd_rek, nm_rek "+
                    " from rekening where level='0' and kd_rek like ? or "+
                    " level='0' and nm_rek like ? order by kd_rek");
            try {
                ps.setString(1,"%"+TCari.getText().trim()+"%");
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    saldojanuari=Sequel.cariIsiAngka2("select saldo_awal from rekeningtahun where thn=? and kd_rek=?",ThnCari.getSelectedItem().toString(),rs.getString("kd_rek"));
                    
                    htmlContent.append(    
                        "<tr class='isi'>"+
                            "<td>"+rs.getString("kd_rek")+"</td>"+
                            "<td>"+rs.getString("nm_rek")+"</td>"+
                            "<td align='right'>"+Valid.SetAngka(saldojanuari)+"</td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                            "<td></td>"+
                        "</tr>"
                    );
                }
            } catch (Exception e) {
                System.out.println("Notif : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML.setText(
                    "<html>"+
                      "<table width='4500px' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("Notif : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());
        
    }
    
    public void isCek(){
        BtnPrint.setEnabled(var.getsaldo_akun_perbulan());
    }
    
}
